---
swagger: "2.0"
info:
  description: "フロント開発用のAPIモック"
  version: "1.0"
  title: "mock-api"
paths:
  /login:
    post:
      summary: "ログイン"
      description: "ID, パスワードを受け取ってセッションIDを返す"
      operationId: "loginPOST"
      parameters: []
      responses:
        "200":
          description: "成功時のレスポンス"
      x-swagger-router-controller: "Default"
  /pet/{petId}:
    get:
      summary: "ペット情報API"
      description: "指定されたpetIdの情報を返します"
      operationId: "petPetIdGET"
      parameters:
      - name: "petId"
        in: "path"
        description: "取得したいペットのID"
        required: true
        type: "integer"
        format: "int64"
      responses:
        "200":
          description: "成功時のレスポンス"
          schema:
            $ref: "#/definitions/inline_response_200"
      x-swagger-router-controller: "Default"
definitions:
  inline_response_200:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      name:
        type: "string"
        example: "doggie"
    example:
      name: "doggie"
      id: 0

