swagger: "2.0"
info:
  description: "フロント開発用のAPIモック"
  version: "1.0"
  title: "mock-api"
paths:
  /login:
    post:
      summary: "ログイン"
      description: "ID, パスワードを受け取ってセッションIDを返す"
      parameters:
        - name: "email"
          description: "メールアドレス"
          required: true
          type: "string"
      responses:
        200:
          description: "成功時のレスポンス"
          schema:
          type: "object"
          properties:
            sid:
              type: "string"
              example: "sssssidddd"
  /pet/{petId}:
    get:
      summary: "ペット情報API"
      description: "指定されたpetIdの情報を返します"
      parameters:
        - name: "petId"
          in: "path"
          description: "取得したいペットのID"
          required: true
          type: "integer"
          format: "int64"
      responses:
        200:
          description: "成功時のレスポンス"
          schema:
            type: "object"
            properties:
              id:
                type: "integer"
                format: "int64"
              name:
                type: "string"
                example: "doggie"
